### ISSUE TITLE
Specify maximum physical size of battery and discuss battery life

### ISSUE THREAD

**Issue by baronunread** [qewer33/qpaperOS#4]
There's different formats for the same mah rating so it should be specified the maximum size of the battery

**Comment by baronunread** [comment]
402030 will work fine

**Comment by qewer33** [comment]
Oop, sorry for the late reply. But yes that should work fine, I think the battery I used is 20x30x5mm. I'll add it to the README.

**Comment by qewer33** [comment]
Also I've somewhat abondoned this project because the LILYGO board used has a couple of dealbreaker power issues. So I never finished the software, if you have problems you can still open issues, I will do my best to help but I can't guarantee anything.

**Comment by baronunread** [comment]
Ah I see, don't worry about it!
I'm definitely trying to play with this myself, I've been looking at the code but as of now I haven't been able to enter the apps menu at all so I'm working my way through things.

Since you're here I wanted to tell you that I really love the idea, I do hope someday there will be a better option for it.

**Comment by donut-but-a-brain** [comment]
@baronunread If you want more accounts of this project, when I did it the battery life was pretty consistently about 4hrs with a 300mah battery and the apps menu worked about once every 20 times I tried to get to it, but it never let me open the WiFi pairing app. If you are willing to give up the apps menu, I forked qpaperOS, renamed it LarryOS (because I planned to do more with it and make it properly my own, but never did), and changed the WiFi setup so you can input your own SSID and password directly to the code when moving it over (make sure to change the timezone as well!). That made the time function work, although it can be a bit finicky when the battery runs out. I never made the weather or anything work, but I might eventually.

**Comment by qewer33** [comment]
> Since you're here I wanted to tell you that I really love the idea, I do hope someday there will be a better option for it.

Yep, same. I was thinking of designing my own pcb at one point but couldn't find a suitable touch e-ink screen :(

**Comment by baronunread** [comment]
@donut-but-a-brain maybe I have a revision of the board but the battery I have (200 mah) has been lasting for more than 4 hours. I left it overnight and it all seems fine, I'm currently sitting at 74%. I ended up yesterday doing exactly what you said and wrote my SSID and pwd inside of the os_config

**Comment by baronunread** [comment]
@donut-but-a-brain I got about a day of battery from 100% to 0%
It seems pretty inconsistent given that @qewer33 initial reported 3-4 days and mine without GPS is about a day...
Is this just a problem of the board?

**Comment by qewer33** [comment]
> Is this just a problem of the board?

Yep, the board's power management is terrible and battery life is super inconsistent. When I was developing the project initially, I remember calculating how much the battery should last with the power usage of the screen + ESP32-S3, it came out around 2 weeks. But obviously that's not the case so something else on the board is wasting a lot of power. I can't confirm but I suspect it's the voltage divider that's used to read the battery capacity.

Here's the board schematics from LILYGO if you want to take a look yourself: https://github.com/Xinyuan-LilyGO/Wrist-E-Paper/blob/main/schematic/Schematic1.pdf

This part of the schematic is likely the problematic part:

![image](https://github.com/user-attachments/assets/b8882798-4670-4d91-a937-21fe3f6c86b6)

(I accidentally edited your comment btw, sorry about that 😅)
