### ISSUE TITLE
Not using RTC getLocalTime after using configTime

### ISSUE THREAD

**Issue by baronunread** [qewer33/qpaperOS#5]
We're not using the RTC, instead we're using the RTC epoch which isn't what we need.

I'm running right now a test PR that uses the RTC and the getLocalTime function instead of saving it to the preferences.

@qewer33 Is there any reason why we're saving it in a variable?

**Comment by qewer33** [comment]
Can you link the relevant code? It's been a while since I've worked on this so I don't really remember any implementation details lol.

**Comment by baronunread** [comment]
@qewer33 lol don't worry at all
https://github.com/qewer33/qpaperOS/blob/a8e3456cc0bbfb866bf4a19ce8c8a9c33839737d/src/wakeup.cpp#L8
https://github.com/qewer33/qpaperOS/blob/a8e3456cc0bbfb866bf4a19ce8c8a9c33839737d/src/wakeup.cpp#L29

This connects to the wifi question and the RTC but epoch and getLocalTime are basically the same thing but LocalTime is configured correctly to have the GMT offset. 

Also you don't need to save to any preference this way 😁

**Comment by qewer33** [comment]
Ah, the RTC epoch is saved to the preferences because the RTC doesn't survive a hard reset. I implemented that to ensure the clock doesn't reset to 00:00 when you press the reset button. The RTC does get preserved in deep sleep so if you look at the wakeupLight function, nothing special is done there (other than saving the RTC to prefs for the next wakeupInit).

I'm not sure if I understand what you are proposing, I'd like to see the code when you make the PR.

**Comment by baronunread** [comment]
By hard reset you mean when you press the reset button right? I'm not sure if that actually does stop the RTC, I'll test that one out by removing the wifi setup at the beginning. 
But regardless when you press the reset button it the esp32 goes through setup again (with INIT state) and there it connects to the wifi and tries to set up configTime.

I do understand the purpose of saving the last saved time though but don't you think that on complete power loss it might be useless since the time would be wrong? Maybe it could be useful to save the time in prefs but only bring it back if the wifi is unavailable after x amount of tries while connecting to wifi/trying to call configTime()

**Comment by qewer33** [comment]
Yeah the reset button does a hard reset. A hard reset can also happen because of software crashes etc. 

And you're right it does attempt to connect to the wifi anyway but if wifi isn't available, then it resets to 00:00 as I said. Also saving the last RTC time isn't really a big deal, we have plenty of memory anyway.

**Comment by baronunread** [comment]
Ah I'm not worried about the memory that's fine obviously.
I'm only thinking about ways where we can reduce operations that are intentionally repeated time after time.
Given your opinion about all of this I would suggest these changes then but first I'd wanna check that the hard reset (not by battery loss) actually does stop the RTC.

- changing the epoch call to getLocalTime, that will sync the RTC to the correct time with the GMT offset
- save the value of the current time right before sleeping
- only set the time at INIT from the saved value if there is no wifi (that logic isn't implemented yet)
